"""add message table2

Revision ID: 7ee8caf1be6e
Revises: e86ca0fb5244
Create Date: 2025-12-14 01:23:11.922438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee8caf1be6e'
down_revision: Union[str, Sequence[str], None] = 'e86ca0fb5244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_message', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('bot_response', sa.String(), nullable=True))
    op.drop_column('messages', 'bot_provider')
    op.drop_column('messages', 'sender')
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.VARCHAR(), nullable=True))
    op.add_column('messages', sa.Column('sender', sa.VARCHAR(), nullable=True))
    op.add_column('messages', sa.Column('bot_provider', sa.VARCHAR(), nullable=True))
    op.drop_column('messages', 'bot_response')
    op.drop_column('messages', 'user_message')
    # ### end Alembic commands ###
